# Generated by Django 5.1.4 on 2025-01-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
