# Generated by Django 5.1.4 on 2025-01-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_transaction_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='subcategory',
        ),
    ]
