# Generated by Django 5.1.4 on 2025-01-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_transaction_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Food & Drinks', [('Bar, cafe', 'Bar, cafe'), ('Groceries', 'Groceries'), ('Restaurant, fast-food', 'Restaurant, fast-food')]), ('Shopping', [('Clothes & Shoes', 'Clothes & Shoes'), ('Drug-store, chemist', 'Drug-store, chemist'), ('Restaurant, fast-food', 'Restaurant, fast-food'), ('Electronics, accessories', 'Electronics, accessories'), ('Free time', 'Free time'), ('Gifts, joy', 'Gifts, joy'), ('Stationary, tools', 'Stationary, tools')]), ('Housing', [('Energy, utilities', 'Energy, utilities'), ('Maintenance, repairs', 'Maintenance, repairs'), ('Property insurance', 'Property insurance'), ('Rent', 'Rent'), ('Services', 'Services')]), ('Transportation', [('Business trips', 'Business trips'), ('Long Distance', 'Long Distance'), ('Public transport', 'Public transport'), ('Taxi', 'Taxi')]), ('Vehicle', [('Fuel', 'Fuel'), ('Leasing', 'Leasing'), ('Parking', 'Parking'), ('Rentals', 'Rentals'), ('Vehicle insurance', 'Vehicle insurance'), ('Vehicle maintenance', 'Vehicle maintenance'), ('Rentals', 'Rentals')]), ('Life & Entertainment', [('Active sport, fitness', 'Active sport, fitness'), ('Alcohol, tobacco', 'Alcohol, tobacco'), ('Books, audio, subscriptions', 'Books, audio, subscriptions'), ('Charity, gifts', 'Charity, gifts'), ('Culture, sport events', 'Culture, sport events'), ('Education, development', 'Education, development'), ('Health care, doctor', 'Health care, doctor'), ('Hobbies', 'Hobbies'), ('Life Events', 'Life Events'), ('Lottery, gambling', 'Lottery, gambling'), ('TV, steaming', 'TV, steaming'), ('Wellness, beauty', 'Wellness, beauty')]), ('Communication, PC', [('Internet', 'Internet'), ('Phone, cell phone', 'Phone, cell phone'), ('Postal services', 'Postal services'), ('Software, apps, games', 'Software, apps, games')]), ('Financial expenses', [('Advisory', 'Advisory'), ('Charges, fees', 'Charges, fees'), ('Postal services', 'Postal services'), ('Child Support', 'Child Support'), ('Fines', 'Fines'), ('Insurances', 'Insurances'), ('Loan, interests', 'Loan, interests'), ('Taxes', 'Taxes')]), ('Investments', [('Collections', 'Collections'), ('Financial Investments', 'Financial Investments'), ('Realty', 'Realty'), ('Savings', 'Savings'), ('Vehicles, chattels', 'Vehicles, chattels')]), ('Income', [('Wage, invoices', 'Wage, invoices'), ('Sale', 'Sale'), ('Checks, coupons', 'Checks, coupons'), ('Child Support', 'Child Support'), ('Dues & grants', 'Dues & grants'), ('Gifts', 'Gifts'), ('Interest, dividents', 'Interest, dividents'), ('Lending, renting', 'Lending, renting'), ('Lottery, gambling', 'Lottery, gambling'), ('Refunds (tax,purchase)', 'Refunds (tax,purchase)'), ('Rental Income', 'Rental Income')]), ('Balance Adjustment', 'Balance Adjustment'), ('Other', 'Other')], max_length=100),
        ),
    ]
