# Generated by Django 5.1.4 on 2025-01-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_wallet_is_predefined_alter_wallet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, default='None', null=True),
        ),
    ]
